-- Migration: 20260325_site_groups_many_to_many
-- Replace sites.group_id (many-to-one) with site_groups table (many-to-many)

-- Step 1: Create the site_groups association table
CREATE TABLE IF NOT EXISTS site_groups (
    site_id  INT NOT NULL,
    group_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (site_id, group_id),
    CONSTRAINT fk_site_groups_site
        FOREIGN KEY (site_id)  REFERENCES sites(id)      ON DELETE CASCADE,
    CONSTRAINT fk_site_groups_group
        FOREIGN KEY (group_id) REFERENCES group_info(id) ON DELETE CASCADE
);

-- Step 2: Migrate existing group_id data into the new association table
INSERT IGNORE INTO site_groups (site_id, group_id)
SELECT id, group_id
FROM sites
WHERE group_id IS NOT NULL;

-- Step 3: Drop the foreign key constraint on sites.group_id
--         (The constraint name was generated by the ORM; find it via:
--          SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
--          WHERE TABLE_NAME = 'sites' AND COLUMN_NAME = 'group_id';)
--         Then replace <fk_constraint_name> below with the actual name.
-- ALTER TABLE sites DROP FOREIGN KEY <fk_constraint_name>;

-- Step 4: Drop the group_id column from sites
-- ALTER TABLE sites DROP COLUMN group_id;
