-- =============================================
-- Construction-Hazard-Detection Database Schema
-- Compatible with PostgreSQL 15+
-- violations.site -> FK to sites(name)
-- =============================================

SET TIME ZONE 'UTC';

DROP TABLE IF EXISTS group_features CASCADE;
DROP TABLE IF EXISTS site_notification_preferences CASCADE;
DROP TABLE IF EXISTS user_sites CASCADE;
DROP TABLE IF EXISTS site_groups CASCADE;
DROP TABLE IF EXISTS stream_configs CASCADE;
DROP TABLE IF EXISTS violations CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS group_info CASCADE;

CREATE TABLE group_info (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    uniform_number VARCHAR(8) UNIQUE NOT NULL,
    max_allowed_streams INTEGER NOT NULL DEFAULT 8,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN group_info.uniform_number IS 'Unified Business Number';

CREATE TABLE features (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    group_id INTEGER,
    CONSTRAINT fk_users_group
        FOREIGN KEY (group_id) REFERENCES group_info(id)
        ON DELETE SET NULL,
    CONSTRAINT chk_users_status CHECK (
        status IN ('active', 'inactive', 'pending')
    )
);
CREATE INDEX idx_users_group ON users (group_id);

CREATE TABLE sites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sites_name UNIQUE (name)
);

CREATE TABLE group_features (
    group_id INTEGER NOT NULL,
    feature_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, feature_id),
    CONSTRAINT fk_gf_group
        FOREIGN KEY (group_id) REFERENCES group_info(id) ON DELETE CASCADE,
    CONSTRAINT fk_gf_feature
        FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
);
CREATE INDEX idx_gf_group ON group_features (group_id);
CREATE INDEX idx_gf_feature ON group_features (feature_id);

CREATE TABLE site_groups (
    site_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (site_id, group_id),
    CONSTRAINT fk_site_groups_site
        FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE,
    CONSTRAINT fk_site_groups_group
        FOREIGN KEY (group_id) REFERENCES group_info(id) ON DELETE CASCADE
);
CREATE INDEX idx_sg_group ON site_groups (group_id);

CREATE TABLE user_profiles (
    user_id INTEGER PRIMARY KEY,
    family_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    given_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    mobile_number VARCHAR(20) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_up_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_sites (
    user_id INTEGER NOT NULL,
    site_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, site_id),
    CONSTRAINT fk_us_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_us_site
        FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_us_user ON user_sites (user_id);
CREATE INDEX idx_us_site ON user_sites (site_id);

CREATE TABLE site_notification_preferences (
    user_id INTEGER NOT NULL,
    site_id INTEGER NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, site_id),
    CONSTRAINT fk_snp_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_snp_site
        FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_snp_site_enabled
    ON site_notification_preferences (site_id, is_enabled);
CREATE INDEX idx_snp_user ON site_notification_preferences (user_id);

CREATE TABLE stream_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    site_id INTEGER NOT NULL,
    stream_name VARCHAR(80) NOT NULL,
    video_url VARCHAR(255) NOT NULL,
    model_key VARCHAR(80) NOT NULL,
    detect_no_safety_vest_or_helmet BOOLEAN DEFAULT FALSE,
    detect_near_machinery_or_vehicle BOOLEAN DEFAULT FALSE,
    detect_in_restricted_area BOOLEAN DEFAULT FALSE,
    detect_in_utility_pole_restricted_area BOOLEAN DEFAULT FALSE,
    detect_machinery_close_to_pole BOOLEAN DEFAULT FALSE,
    detect_with_server BOOLEAN DEFAULT TRUE,
    expire_date TIMESTAMP WITH TIME ZONE,
    work_start_hour INTEGER,
    work_end_hour INTEGER,
    store_in_redis BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sc_group
        FOREIGN KEY (group_id) REFERENCES group_info(id) ON DELETE CASCADE,
    CONSTRAINT fk_sc_site
        FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE,
    CONSTRAINT uq_sc_site_stream UNIQUE (site_id, stream_name)
);
CREATE INDEX idx_sc_group ON stream_configs (group_id);
CREATE INDEX idx_sc_site ON stream_configs (site_id);

CREATE TABLE violations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name VARCHAR(80) NOT NULL,
    detection_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_path VARCHAR(255) NOT NULL,
    detections_json TEXT,
    cone_polygon_json TEXT,
    pole_polygon_json TEXT,
    warnings_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    site VARCHAR(80) NOT NULL,
    CONSTRAINT fk_vio_site_name
        FOREIGN KEY (site) REFERENCES sites(name) ON DELETE CASCADE
);
CREATE INDEX idx_vio_site_name ON violations (site);
CREATE INDEX idx_vio_time ON violations (detection_time);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_group_info_updated_at
BEFORE UPDATE ON group_info
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_features_updated_at
BEFORE UPDATE ON features
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sites_updated_at
BEFORE UPDATE ON sites
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_profiles_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_site_notification_preferences_updated_at
BEFORE UPDATE ON site_notification_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_stream_configs_updated_at
BEFORE UPDATE ON stream_configs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO group_info (id, name, uniform_number, max_allowed_streams)
VALUES (1, 'Default Group', '00000001', 8)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    max_allowed_streams = EXCLUDED.max_allowed_streams;

SELECT setval(
    pg_get_serial_sequence('group_info', 'id'),
    GREATEST((SELECT MAX(id) FROM group_info), 1)
);

INSERT INTO features (feature_name, description)
VALUES ('yolo_api', 'Utilising YOLO for real-time object detection.')
ON CONFLICT (feature_name) DO UPDATE SET
    description = EXCLUDED.description;

INSERT INTO users (username, password_hash, role, status, group_id)
VALUES (
    'user',
    '$argon2id$v=19$m=65536,t=3,p=4$WWrgNzRESjrJxeP6KC+jsQ$LRWIP3bk3vAJf5kSEA+gkSk1+KYvVU2VDwCKGiUtBCg',
    'admin',
    'active',
    1
)
ON CONFLICT (username) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    group_id = EXCLUDED.group_id;

INSERT INTO group_features (group_id, feature_id)
SELECT 1, f.id
FROM features f
WHERE f.feature_name = 'yolo_api'
ON CONFLICT (group_id, feature_id) DO NOTHING;
