from __future__ import annotations

LANGUAGES = {
    'zh-TW': {
        'warning_people_in_controlled_area': '警告: 有{count}個人進入受控區域!',
        'warning_no_hardhat': '警告: 有人無配戴安全帽!',
        'warning_no_safety_vest': '警告: 有人無穿著安全背心!',
        'warning_close_to_machinery': '警告: 有人過於靠近{label}!',
        'label_machinery': '機具',
        'label_vehicle': '車輛',
    },
    'zh-CN': {
        'warning_people_in_controlled_area': '警告: 有{count}个人进入受控区域!',
        'warning_no_hardhat': '警告: 有人未佩戴安全帽!',
        'warning_no_safety_vest': '警告: 有人未穿着安全背心!',
        'warning_close_to_machinery': '警告: 有人过于靠近{label}!',
        'label_machinery': '机械',
        'label_vehicle': '车辆',
    },
    'en': {
        'warning_people_in_controlled_area': 'Warning: {count} people have entered the controlled area!',
        'warning_no_hardhat': 'Warning: Someone is not wearing a hardhat!',
        'warning_no_safety_vest': 'Warning: Someone is not wearing a safety vest!',
        'warning_close_to_machinery': 'Warning: Someone is too close to {label}!',
        'label_machinery': 'machinery',
        'label_vehicle': 'vehicle',
    },
    'fr': {
        'warning_people_in_controlled_area': 'Avertissement: {count} personnes sont entrées dans la zone contrôlée!',
        'warning_no_hardhat': "Avertissement: Quelqu'un ne porte pas de casque!",
        'warning_no_safety_vest': "Avertissement: Quelqu'un ne porte pas de gilet de sécurité!",
        'warning_close_to_machinery': 'Avertissement: Quelqu’un est trop proche de {label}!',
        'label_machinery': 'machinerie',
        'label_vehicle': 'véhicule',
    },
    'vi': {
        'warning_people_in_controlled_area': 'Cảnh báo: Có {count} người đã vào khu vực kiểm soát!',
        'warning_no_hardhat': 'Cảnh báo: Có người không đội mũ bảo hộ!',
        'warning_no_safety_vest': 'Cảnh báo: Có người không mặc áo gi-lê an toàn!',
        'warning_close_to_machinery': 'Cảnh báo: Có người quá gần với {label}!',
        'label_machinery': 'máy móc',
        'label_vehicle': 'phương tiện',
    },
    'id': {
        'warning_people_in_controlled_area': 'Peringatan: {count} orang telah memasuki area terkontrol!',
        'warning_no_hardhat': 'Peringatan: Seseorang tidak mengenakan helm!',
        'warning_no_safety_vest': 'Peringatan: Seseorang tidak mengenakan rompi keselamatan!',
        'warning_close_to_machinery': 'Peringatan: Seseorang terlalu dekat dengan {label}!',
        'label_machinery': 'mesin',
        'label_vehicle': 'kendaraan',
    },
    'th': {
        'warning_people_in_controlled_area': 'คำเตือน: มี {count} คนเข้ามาในพื้นที่ควบคุม!',
        'warning_no_hardhat': 'คำเตือน: มีคนไม่สวมหมวกนิรภัย!',
        'warning_no_safety_vest': 'คำเตือน: มีคนไม่สวมเสื้อกั๊กนิรภัย!',
        'warning_close_to_machinery': 'คำเตือน: มีคนอยู่ใกล้ {label} มากเกินไป!',
        'label_machinery': 'เครื่องจักร',
        'label_vehicle': 'ยานพาหนะ',
    },
}
